---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
#load dataset
if(!file.exists('activity.csv')){
    unzip('activity.zip')
}
activity <- read.csv('activity.csv')
```


## What is mean total number of steps taken per day?

```{r}
#Calculate the total number of steps taken per day
#totalSteps <- tapply(activity$steps, activity$date, FUN=sum, na.rm=TRUE)
interval_totalSteps <- aggregate(x=list(steps=activity$steps), by=list(interval=activity$date), 
                        FUN=sum, na.rm=TRUE)

#Make a histogram of the total number of steps taken each day
library(ggplot2)
qplot(interval_totalSteps$steps, xlab='Sum of steps per day', ylab='Count', binwidth=500)

#Calculate and report the mean and median of the total number of steps taken per day
mean_stepsPerDay <- mean(interval_totalSteps$steps)
median_stepsPerDay <- median(interval_totalSteps$steps)
```


## What is the average daily activity pattern?
```{r}
average_stepsPerDay <- aggregate(x=list(steps=activity$steps),
                                 by=list(interval=activity$interval),
                                 FUN=mean, na.rm=TRUE)
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
